INSERT INTO SETTINGS(NAME, CONTENT) VALUES ('title','Site Exemplo');
INSERT INTO SETTINGS(NAME, CONTENT) VALUES ('subtitle','Criado pelo usuário');
INSERT INTO SETTINGS(NAME, CONTENT) VALUES ('email','contato@sevensystems.com.br');
INSERT INTO SETTINGS(NAME, CONTENT) VALUES ('bgColor','#000000');
INSERT INTO SETTINGS(NAME, CONTENT) VALUES ('textColor','#FFFFFF');